change Kangie script another commit https://gitlab.com/Matt.Jolly/kangie-gentoo-scripts/-/commit/69d2c4bf6d3160a7b802471e1cb7cd48a79847ef

diff --git a/gentoo-chroot b/gentoo-chroot
--- a/gentoo-chroot
+++ b/gentoo-chroot
@@ -1,5 +1,20 @@
-#!/bin/bash
-# Shamelessly "borrowed" from arch to make Gentoo development in chroots easier
+#!/usr/bin/env bash
+# Shamelessly "borrowed" from Arch to make Gentoo development in chroots easier;
+# Thanks for doing all of the hard work!
+
+# Usage:
+#   Run this script with either flags or appropriate ENVVARS set and provide it with the directory
+#   that you want to chroot into, and it will handle all of the tedium.
+
+# Options:
+#   -b | --bind-binpkgs | MOUNT_BINPKGS
+#   -d | --debug
+#   -k | --no-bind-kernel | NO_MOUNT_KERNEL_SOURCE=1
+#   -m | --bind-makeconf | MOUNT_MAKECONF
+#   -n | --no-bashrc | NO_MOUNT_BASHRC
+#   -N | --unshare
+#   -r | --bind-hostrepos | MOUNT_HOSTREPOS
+#   -u | --user | USERSPEC=user[:group]
 
 shopt -s extglob
 
@@ -78,8 +93,8 @@ declare -A fsck_types=([btrfs]=1
                        [xfs]=1)
 
 out() { printf "$1 $2\n" "${@:3}"; }
-error() { out "==> ERROR:" "$@"; } >&2
-warning() { out "==> WARNING:" "$@"; } >&2
+error() { out "==> \033[1;31mERROR\033[0m:" "$@"; } >&2
+warning() { out "==> \033[1;33mWARNING\033[0m:" "$@"; } >&2
 msg() { out "==>" "$@"; }
 msg2() { out "  ->" "$@";}
 die() { error "$@"; exit 1; }
@@ -122,7 +137,6 @@ chroot_setup() {
   chroot_add_mount shm "$1/dev/shm" -t tmpfs -o mode=1777,nosuid,nodev &&
   chroot_add_mount run "$1/run" -t tmpfs -o nosuid,nodev,mode=0755 &&
   chroot_add_mount tmp "$1/tmp" -t tmpfs -o mode=1777,strictatime,nodev,nosuid
-  chroot_bind_device /var/db/repos/gentoo "${1}/var/db/repos/gentoo"
 }
 
 chroot_teardown() {
@@ -137,8 +151,9 @@ chroot_add_mount_lazy() {
 }
 
 chroot_bind_device() {
-  touch "$2" && CHROOT_ACTIVE_FILES=("$2" "${CHROOT_ACTIVE_FILES[@]}")
-  chroot_add_mount $1 "$2" --bind
+  local DEVICE="${CHROOT_DIR}/$1"
+  touch "${DEVICE}" && CHROOT_ACTIVE_FILES=("${DEVICE}" "${CHROOT_ACTIVE_FILES[@]}")
+  chroot_add_mount $1 "${DEVICE}" --bind
 }
 
 chroot_add_link() {
@@ -152,21 +167,21 @@ unshare_setup() {
   [[ $(trap -p EXIT) ]] && die '(BUG): attempting to overwrite existing EXIT trap'
   trap 'unshare_teardown' EXIT
 
-  chroot_add_mount_lazy "${1}" "${1}" --bind &&
-  chroot_add_mount proc "${1}/proc" -t proc -o nosuid,noexec,nodev &&
-  chroot_add_mount_lazy /sys "${1}/sys" --rbind &&
-  chroot_add_link "${1}/proc/self/fd" "${1}/dev/fd" &&
-  chroot_add_link "${1}/proc/self/fd/0" "${1}/dev/stdin" &&
-  chroot_add_link "${1}/proc/self/fd/1" "${1}/dev/stdout" &&
-  chroot_add_link "${1}/proc/self/fd/2" "${1}/dev/stderr" &&
-  chroot_bind_device /dev/full "${1}/dev/full" &&
-  chroot_bind_device /dev/null "${1}/dev/null" &&
-  chroot_bind_device /dev/random "${1}/dev/random" &&
-  chroot_bind_device /dev/tty "${1}/dev/tty" &&
-  chroot_bind_device /dev/urandom "${1}/dev/urandom" &&
-  chroot_bind_device /dev/zero "${1}/dev/zero" &&
-  chroot_add_mount run "${1}/run" -t tmpfs -o nosuid,nodev,mode=0755 &&
-  chroot_add_mount tmp "${1}/tmp" -t tmpfs -o mode=1777,strictatime,nodev,nosuid
+  chroot_add_mount_lazy "${CHROOT_DIR}" "${CHROOT_DIR}" --bind &&
+  chroot_add_mount proc "${CHROOT_DIR}/proc" -t proc -o nosuid,noexec,nodev &&
+  chroot_add_mount_lazy /sys "${CHROOT_DIR}/sys" --rbind &&
+  chroot_add_link "${CHROOT_DIR}/proc/self/fd" "${CHROOT_DIR}/dev/fd" &&
+  chroot_add_link "${CHROOT_DIR}/proc/self/fd/0" "${CHROOT_DIR}/dev/stdin" &&
+  chroot_add_link "${CHROOT_DIR}/proc/self/fd/CHROOT_DIR" "${CHROOT_DIR}/dev/stdout" &&
+  chroot_add_link "${CHROOT_DIR}/proc/self/fd/2" "${CHROOT_DIR}/dev/stderr" &&
+  chroot_bind_device /dev/full &&
+  chroot_bind_device /dev/null &&
+  chroot_bind_device /dev/random &&
+  chroot_bind_device /dev/tty &&
+  chroot_bind_device /dev/urandom &&
+  chroot_bind_device /dev/zero &&
+  chroot_add_mount run "${CHROOT_DIR}/run" -t tmpfs -o nosuid,nodev,mode=0755 &&
+  chroot_add_mount tmp "${CHROOT_DIR}/tmp" -t tmpfs -o mode=1777,strictatime,nodev,nosuid
 }
 
 unshare_teardown() {
@@ -183,8 +198,8 @@ unshare_teardown() {
   unset CHROOT_ACTIVE_FILES
 }
 
-pid_unshare="unshare --fork --pid"
-mount_unshare="$pid_unshare --mount --map-auto --map-root-user --setuid 0 --setgid 0"
+PID_UNSHARE="unshare --fork --pid"
+MOUNT_UNSHARE="$PID_UNSHARE --mount --map-auto --map-root-user --setuid 0 --setgid 0"
 
 # This outputs code for declaring all variables to stdout. For example, if
 # FOO=BAR, then running
@@ -358,30 +373,6 @@ fstype_has_fsck() {
   (( fsck_types["$1"] ))
 }
 
-
-setup=chroot_setup
-unshare=0
-
-usage() {
-  cat <<EOF
-usage: ${0##*/} chroot-dir [command] [arguments...]
-
-    -h                  Print this help message
-    -N                  Run in unshare mode as a regular user
-    -u <user>[:group]   Specify non-root user and optional group to use
-
-If 'command' is unspecified, ${0##*/} will launch /bin/bash.
-
-Note that when using gentoo-chroot, the target chroot directory *should* be a
-mountpoint. This ensures that tools such as pacman(8) or findmnt(8) have an
-accurate hierarchy of the mounted filesystems within the chroot.
-
-If your chroot target is not a mountpoint, you can bind mount the directory on
-itself to make it a mountpoint, i.e. 'mount --bind /your/chroot /your/chroot'.
-
-EOF
-}
-
 resolve_link() {
   local target=$1
   local root=$2
@@ -399,89 +390,156 @@ resolve_link() {
   printf %s "$target"
 }
 
-chroot_add_resolv_conf() {
-  local chrootdir=$1
-  local src=$(resolve_link /etc/resolv.conf)
-  local dest=$(resolve_link "$chrootdir/etc/resolv.conf" "$chrootdir")
+# Mount arbitrary files into your chroot
+# usage: chroot_add_file src-file[:dst-file]
+# gets CHROOT_DIR from environment
+chroot_add_file() {
+  local SRC_FILE
+  local DST_FILE
+  if [[ "${1}" == *:* ]]; then
+    # Bind src -> dest
+    SRC_FILE=${1%:*}
+    DST_FILE=${1#*:}
+    SRC_FILE=$(resolve_link "${SRC_FILE}")
+    DST_FILE=$(resolve_link "${CHROOT_DIR}/${DST_FILE}" "${CHROOT_DIR}")
+  else
+    SRC_FILE=$(resolve_link "${1}")
+    DST_FILE=$(resolve_link "$CHROOT_DIR/$1" "$CHROOT_DIR")
+  fi
 
-  # If we don't have a source resolv.conf file, there's nothing useful we can do.
-  [[ -e $src ]] || return 0
+  # If we don't have a source file, there's nothing useful we can do.
+  [[ -e ${SRC_FILE} ]] || return 0
 
-  if [[ ! -e $dest ]]; then
+  if [[ ! -e $DST_FILE ]]; then
     # There are two reasons the destination might not exist:
     #
-    #   1. There may be no resolv.conf in the chroot.  In this case, $dest won't exist,
-    #      and it will be equal to $1/etc/resolv.conf.  In this case, we'll just exit.
-    #      The chroot environment must not be concerned with DNS resolution.
+    #   1. There may be no destination file in the chroot.  In this case, $DST_FILE won't exist,
+    #      and it will be equal to $CHROOT_DIR/$1.  In this case, we'll just exit.
     #
-    #   2. $1/etc/resolv.conf is (or resolves to) a broken link.  The environment
-    #      clearly intends to handle DNS resolution, but something's wrong.  Maybe it
+    #   2. $1/$2 is (or resolves to) a broken link.  The environment
+    #      clearly intends for there to be a file here, but something's wrong.  Maybe it
     #      normally creates the target at boot time.  We'll (try to) take care of it by
     #      creating a dummy file at the target, so that we have something to bind to.
 
     # Case 1.
-    [[ $dest = $chrootdir/etc/resolv.conf ]] && return 0
+    [[ ${DST_FILE} = "${CHROOT_DIR}/${1}" ]] && return 0
 
     # Case 2.
-    install -Dm644 /dev/null "$dest" || return 1
+    install -Dm644 /dev/null "${DST_FILE}" || return 1
   fi
 
-  chroot_add_mount "$src" "$dest" --bind
+  chroot_add_mount "${SRC_FILE}" "${DST_FILE}" --bind
 }
-
-while getopts ':hNu:' flag; do
-  case $flag in
-    h)
-      usage
-      exit 0
-      ;;
-    N)
-      setup=unshare_setup
-      unshare=1
-      ;;
-    u)
-      userspec=$OPTARG
-      ;;
-    :)
-      die '%s: option requires an argument -- '\''%s'\' "${0##*/}" "$OPTARG"
-      ;;
-    ?)
-      die '%s: invalid option -- '\''%s'\' "${0##*/}" "$OPTARG"
-      ;;
-  esac
-done
-shift $(( OPTIND - 1 ))
-
-(( $# )) || die 'No chroot directory specified'
-chrootdir=$1
-shift
 
 gentoo-chroot() {
-  (( EUID == 0 )) || die 'This script must be run with root privileges'
+  (( EUID == 0 )) || die "This script must be run with root privileges"
 
-  [[ -d $chrootdir ]] || die "Can't create chroot on non-directory %s" "$chrootdir"
+  [[ -d $CHROOT_DIR ]] || die "Can't create chroot on non-directory %s" "$CHROOT_DIR"
 
-  $setup "$chrootdir" || die "failed to setup chroot %s" "$chrootdir"
-  chroot_add_resolv_conf "$chrootdir" || die "failed to setup resolv.conf"
+  $SETUP "$CHROOT_DIR" || die "failed to setup chroot %s" "$CHROOT_DIR"
 
-  if ! mountpoint -q "$chrootdir"; then
-    warning "$chrootdir is not a mountpoint. This may have undesirable side effects."
+  local CHROOT_FILES=( )
+  # Allow the use of $ADDITIONAL_CHROOT_FILES to mount arbirary files from a running env
+  if [ ! ${#ADDITIONAL_CHROOT_FILES[@]} -eq 0 ]; then
+    $CHROOT_FILES=$ADDITIONAL_CHROOT_FILES
+  fi
+  CHROOT_FILES+=( "/etc/resolv.conf" )
+  if [ -z ${NO_MOUNT_BASHRC+x} ]; then
+    # Grab our bashrc which does useful gentoo functions like env-update and setting $PS1
+    CHROOT_FILES+=( "${FILES_DIR}/bashrc:/root/.bashrc" )
+  fi
+  if ! [ -z ${MOUNT_MAKECONF+x} ]; then
+    CHROOT_FILES+=( "/etc/portage/make.conf" )
   fi
 
-  chroot_args=()
-  [[ $userspec ]] && chroot_args+=(--userspec "$userspec")
+  for FILE in ${CHROOT_FILES[@]}; do
+      chroot_add_file "${FILE}" || die "failed to setup ${FILE}"
+  done
 
-  if [ ${#args[@]} -eq 0 ]; then
-    SHELL=/bin/bash $pid_unshare chroot "${chroot_args[@]}" -- "$chrootdir"
+  # Try and avoid redundant downloads by bringing in distfiles from our host
+  chroot_bind_device /var/cache/distfiles "${CHROOT_DIR}/var/cache/distfiles"
+
+  # Honour user flags or envvars
+  if ! [ -z ${MOUNT_KERNEL_SOURCE+x} ]; then
+    chroot_bind_device /usr/src/linux "${CHROOT_DIR}/usr/src/linux"
+  fi
+  if ! [ -z ${MOUNT_HOST_REPOS+x} ]; then
+    chroot_bind_device /etc/portage/repos.conf "${CHROOT_DIR}/etc/portage/repos.conf"
+    chroot_bind_device /var/db/repos "${CHROOT_DIR}/var/db/repos"
   else
-    $pid_unshare chroot "${chroot_args[@]}" -- "$chrootdir" /bin/bash -c "source /etc/profile && env-update && ${args[@]}"
+    chroot_bind_device /var/db/repos/gentoo "${CHROOT_DIR}/var/db/repos/gentoo"
+  fi
+  if [ -d "/var/cache/binpkgs"  ] && ! [ -z ${MOUNT_BINPKGS+x} ]; then
+    chroot_bind_device /var/cache/binpkgs "${CHROOT_DIR}/var/cache/binpkgs"
   fi
 
+  if ! mountpoint -q "$CHROOT_DIR"; then
+    warning "$CHROOT_DIR is not a mountpoint. This may have undesirable side effects."
+  fi
+
+  CHROOT_ARGS=()
+  [[ $USERSPEC ]] && CHROOT_ARGS+=(--userspec "$USERSPEC")
+  if [ ${#ARGS[@]} -eq 0 ]; then
+    SHELL=/bin/bash $PID_UNSHARE chroot "${CHROOT_ARGS[@]}" -- "$CHROOT_DIR"
+  else
+    $PID_UNSHARE chroot "${CHROOT_ARGS[@]}" -- "$CHROOT_DIR" "${ARGS[@]}"/bin/bash -c "source /etc/profile && env-update && ${args[@]}"
+  fi
 }
 
-args=("$@")
-if (( unshare )); then
-  $mount_unshare bash -c "$(declare_all); gentoo-chroot"
+# Default to chroot; do unshare if user requests it
+SETUP=chroot_setup
+
+usage() {
+  cat <<EOF
+Usage: ${0##*/} options /path/to/chroot command
+Options: [ -b | --bind-binpkgs ] [ -d | --debug ] [-k | --no-bind-kernel] [ -m | --bind-makeconf ]
+         [ -n | --no-bashrc ] [ -N | --unshare ] [ -r | --bind-hostrepos ] [ -u | --user <user>[:group] ]
+
+If 'command' is unspecified, ${0##*/} will launch /bin/bash.
+
+Note that when using ${0##*/}, the target chroot directory *should* be a
+mountpoint. This ensures that tools such as findmnt(8) have an
+accurate hierarchy of the mounted filesystems within the chroot.
+
+If your chroot target is not a mountpoint, you can bind mount the directory on
+itself to make it a mountpoint, i.e. 'mount --bind /your/chroot /your/chroot'.
+
+EOF
+  exit 2
+}
+
+PARSED_ARGS=$(getopt -a -n ${0##*/} -o bdkmnNru: --long bind-binpkgs,debug,no-bind-kernel,bind-makeconf,no-bashrc,unshare,bind-hostrepos,user: -- "$@")
+eval set -- "$PARSED_ARGS"
+while :
+do
+  case "$1" in
+    -b | --bind-binpkgs ) MOUNT_BINPKGS=1 ; shift ;;
+    -d | --debug ) DEBUG=1; echo -e "\e[1;35mEnabling very-basic debug!\e[0m"; set -x; shift ;;
+    -k | --no-bind-kernel) NO_MOUNT_KERNEL_SOURCE=1; shift ;;
+    -m | --bind-makeconf ) MOUNT_MAKECONF=1 ; shift ;;
+    -n | --no-bashrc ) NO_MOUNT_BASHRC=1 ; shift ;;
+    -N | --unshare ) DO_UNSHARE=1 ; SETUP=unshare_setup ; shift ;;
+    -r | --bind-hostrepos ) MOUNT_HOSTREPOS=1 ; shift ;;
+    -u | --user ) USERSPEC="${2}"; shift 2 ;;
+    -- ) shift ; break ;;
+  esac
+done
+
+if [ $# -eq 0 ]; then
+  usage
+  die "No chroot directory specified"
+fi
+
+CHROOT_DIR=$1
+shift
+ARGS=("$@")
+
+if [ -z ${FILES_DIR+x} ]; then
+  FILES_DIR="$(dirname "$(readlink -f "$0")")"
+fi
+
+if ! [ -z ${DO_UNSHARE+x} ]; then
+  $MOUNT_UNSHARE bash -c "$(declare_all); gentoo-chroot"
 else
   gentoo-chroot
 fi
